CREATE TABLE folders (
    folder_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    folder_title TEXT NOT NULL UNIQUE
);

CREATE TABLE notes (
    note_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY ,
    note_name TEXT NOT NULL,
    note_content TEXT NOT NULL,
    folder_id INTEGER
        REFERENCES folders(folder_id) NOT NULL
);